blog/urls.py
from django.urls import path
from.import views
app_name = "blog"

urlpatterns = [
    path("",views.blog_list,name = "blog_list"),
    path("blog/<int:id>",views.blog_detail,name = "blog_detail"),
    path("tag/<slug:tag>",views.blog_tag,name = "tag"),
    path("category/<slug:category>",views.blog_category,name = "category"),
    path("search/",views.search,name = "search")
]

foods/urls.py
from django.urls import path
from .import views
app_name = "foods"

urlpatterns = [
    path("",views.food_list,name = "food_list"),
    path("<int:id>/",views.food_details,name = "food_details")
]

reservation/urls.py
from django.urls import path
from .import views

app_name = "reservation"

urlpatterns = [
    path('',views.reserve,name = "reserve")
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls')),
    path('book/', include('reservation.urls')),
    path("blog/",include("blog.urls")),
  
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


# Create your models here.

class Blog(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    description = models.CharField(_("توضیحات"), max_length=100)
    content = models.TextField(_("متن"))
    created_at = models.DateTimeField(_("زمان انتشار"), default=timezone.now)
    author = models.ForeignKey(User, verbose_name=_("نویسنده"), on_delete=models.CASCADE)
    image = models.ImageField(_("تصویر"), upload_to="blogs/", blank = True , null = True)
    category = models.ForeignKey("Category", related_name="blog" , verbose_name=_("دسته بندی"), on_delete=models.CASCADE,blank=True, null=True)
    tags = models.ManyToManyField("Tag", verbose_name=_("تگ ها"),related_name="blogs",blank=True,null=True)
    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.title
    
class Tag(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    update_at = models.DateTimeField(_("تاریخ برزرسانی"), auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title
    
class Comments(models.Model):
    blog = models.ForeignKey("Blog", verbose_name=_("مقاله"), related_name="comments" , on_delete=models.CASCADE)
    name = models.CharField(_("نام کاربر"), max_length=100)
    email = models.EmailField(_("آدرس الکترونیکی"), max_length=254)
    message = models.TextField(_("متن نظر"))
    date = models.DateField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"

    def __str__(self):
        return self.email

contact/models.py
from django.db import models

# Create your models here.

foods/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class food(models.Model):
    FOOD_TYPE = [
        ("breakfast","صبحانه"),
        ("drinks","نوشیدنی ها"),
        ("dinner","شام"),
        ("lunch","ناهار")
    ]
    name = models.CharField(max_length=  100)
    description = models.CharField(_("توضیحات"),max_length=50)
    rate = models.IntegerField(_("امتیاز"),default=0)
    price = models.IntegerField()
    time = models.IntegerField(_("زمان لازم"))
    pop_date = models.DateField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    photo = models.ImageField(upload_to = 'foods/')
    type_food = models.CharField(_("نوع غذا"),max_length=10,choices=FOOD_TYPE,default="lunch")

    class Meta:
        verbose_name = "غذا"
        verbose_name_plural = "غذاها"
    def __str__(self):
        return self.name

reservation/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Reservation(models.Model):
    name = models.CharField(_("نام و نام خانوادگی"), max_length=200)
    email = models.EmailField(_("آدرس الکترونیکی"), max_length=254)
    phone = models.CharField(_("تلفن"), max_length=20)
    number = models.IntegerField(_("تعداد"))
    date = models.DateField(_("تاریخ"), auto_now=False, auto_now_add=False)
    time = models.TimeField(_("ساعت"), auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.email

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(widget=forms.Textarea)

reservation/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = "__all__"

blog/views.py
from django.shortcuts import render
from .models import Blog , Tag , Category , Comments
from .forms import CommentForm
from django.core.paginator import Paginator

# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs,3)
    page_number = request.GET.get('page')
    blog_list = paginator.get_page(page_number)
    context = {
        "Blog_list" : blog_list
    }

    return render(request,"blog/blog_list.html",context)
def blog_detail(request, id):
    blog = Blog.objects.get(id=id)
    tags = Tag.objects.all().filter(blogs=blog)
    recent = Blog.objects.all().order_by("created_at")[:5]
    category = Category.objects.all()
    comments = Comments.objects.all().filter(blog=blog)
    
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data['name']
            new_email = form.cleaned_data["email"]
            new_message = form.cleaned_data["message"]

            new_comment = Comments(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()
    context = {
        "Blog" : blog,
        "Tags" : tags,
        "Recent" : recent,
        "Category" : category,
        "Comments" : comments,
    }
    return render(request,"blog/blog_detail.html",context)

def blog_tag(request,tag):
    blogs = Blog.objects.filter(tags__slug=tag)
    context = {
        "Blogs" : blogs
    }

    return render(request,"blog/blog_list.html",context)

def blog_category(request,category):
    blogs = Blog.objects.filter(Category__slug=category)
    context = {
        "Blogs" : blogs
    }

    return render(request,"blog/blog_list.html",context)

def search(request):
    if request.method == "GET":
        q = request.GET.get("search")
    blog_list = Blog.objects.filter(title__icontains=q)
    return render(request,"blog/blog_list.html",{"Blog_list":blog_list})

contact/views.py
from django.shortcuts import render

# Create your views here.

foods/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import food
# Create your views here.

def food_list(request):
    food_list = food.objects.all()
    context = {
        "foods" : food_list
    }
    return render(request,"foods/list.html",context)

def food_details(request , id):

    food_details = food.objects.get(id=id)
    context = {
        "foods" : food_details
    }
    return render(request,"foods/details.html",context)

reservation/views.py
from django.shortcuts import render
from .forms import ReservationForm

# Create your views here.

def reserve(request):
    reserve_form = ReservationForm()
    if request.method == "POST":
        reserve_form = ReservationForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()
    else:
        reserve_form = ReservationForm()

    context = {
        "form":reserve_form,
    }

    return render(request,"reservation/reservation.html",context)

blog/templates/blog/blog_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Blog</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

<!-- Start blog details -->
<div class="blog-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>{{Blog.title}}</h2>
                    <p>{{Blog.description}}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-12">
                <div class="blog-inner-details-page">
                    <div class="blog-inner-box">
                        <div class="side-blog-img">
                            <img class="img-fluid" src="{{Blog.image.url}}" style="height: 400px;width: 600px;" alt="">
                            <div class="date-blog-up">
                                27 Fab
                            </div>
                        </div>
                        <div class="inner-blog-detail details-page">
                            <h3></h3>
                            <ul>
                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{Blog.author.first_name}}</span></li>
                                <li>|</li>
                                <li><i class="zmdi zmdi-time"></i>Time : <span>{{Blog.created_at|time}}</span></li>
                            </ul>
                            <p dir="rtl">{{Blog.content}}</p>
                        </div>
                    </div>
                    <div class="blog-comment-box">
                        <h3>Comments</h3>
                        {% for comment in Comments %}
                        <div class="comment-item">
                            <div class="comment-item-left">
                                <img src="images/avt-img.jpg" alt="">
                            </div>
                            <div class="comment-item-right">
                                <div class="pull-left">
                                    <a href="#">{{comment.name}}</a>
                                </div>
                                <div class="pull-right">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{comment.date}}</span>
                                </div>
                                <div class="des-l">
                                    <p align=right>{{comment.message}}</p>
                                </div>
                                <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    <div class="comment-respond-box">
                        <h3>Leave your comment </h3>
                        <div class="comment-respond-form">
                            <form id="commentrespondform" class="comment-form-respond row" method="post">
                                {% csrf_token %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
                                    </div>
                                    <div class="form-group">
                                        <input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <textarea class="form-control" name="message" id="textarea_com" placeholder="Your Message" rows="2"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button class="btn btn-submit">Submit comment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
                <div class="right-side-blog">
                    <h3>Search</h3>
                    <form method="GET" action="{% url 'blog:search' %}">
                        <div class="blog-search-form">
                            <input name="search" placeholder="Search blog" type="text">
                            <button class="search-btn" , type="submit">
								<i class="fa fa-search" aria-hidden="true"></i>
							</button>
                        </div>
                    </form>
                    <h3>دسته بندی ها</h3>
                    <div class="blog-categories">
                        <ul>
                            {% for category in Category %}
                            <li><a href="{% url 'blog:category' category.slug %}"><span>{{category.title}}</span></a></li>
                            {% endfor %}

                        </ul>
                    </div>
                    <h3>پست های اخیر</h3>
                    <div class="post-box-blog">
                        <div class="recent-post-box">
                            {% for Blog in Recent %}
                            <div class="recent-box-blog">
                                <div class="recent-img">
                                    <img class="img-fluid" src="{{Blog.image.url}}" style="height: 70px;width: 70px;" alt="">
                                </div>
                                <div class="recent-info">
                                    <ul>
                                        <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{Blog.author}}</span></li>
                                        <li>|</li>
                                        <li><i class="zmdi zmdi-time"></i>Time : <span>{{Blog.created_at|time}}</span></li>
                                    </ul>
                                    <h4>{{Blog.description}}</h4>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <h3>Recent Tag</h3>
                    <div class="blog-tag-box">
                        <ul class="list-inline tag-list">
                            {% for tag in Tags %}
                            <li class="list-inline-item"><a href="{% url 'blog:tag' tag.slug %}">{{tag.title}}</a></li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- End details -->
{% endblock content %}

foods/templates/foods/details.html
{% extends 'base.html' %}

{% block content %}

    <img width="50%" src="{{foods.photo.url}}" alt="">
    {{foods.name}}
    {{foods.description}}
    {{foods.price}}

{% endblock content %}

foods/templates/foods/list.html
{% extends 'base.html' %}
{% load static %}
	
	{% block content %}
    <!-- Start slides -->
	<div id="slides" class="cover-slides">
		<ul class="slides-container">
			<li class="text-center">
				<img src="{% static 'images/slider-01.jpg' %}" alt="">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h1 class="m-b-20"><strong>به رستوران <br> سید جمال الدین خوش آمدید</strong></h1>
							<p class="m-b-40">میز خود را رزرو کنید</p>
							<p><a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:reserve' %}">رزرو میز</a></p>
						</div>
					</div>
				</div>
			</li>
			<li class="text-center">
				<img src="{% static 'images/slider-02.jpg' %}" alt="">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h1 class="m-b-20"><strong>به رستوران <br> سید جمال الدین خوش آمدید</strong></h1>
							<p class="m-b-40">منوی ویژه را ملاحضه کنید</p>
							<p><a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:reserve' %}">رزرو میز</a></p>
						</div>
					</div>
				</div>
			</li>
			<li class="text-center">
				<img src="{% static 'images/slider-03.jpg' %}" alt="">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h1 class="m-b-20"><strong>به رستوران <br> سید جمال الدین خوش آمدید</strong></h1>
							<p class="m-b-40">مقاله ها را بخوانید</p>
							<p><a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:reserve' %}">رزرو میز</a></p>
						</div>
					</div>
				</div>
			</li>
		</ul>
		<div class="slides-navigation">
			<a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
			<a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
		</div>
	</div>
	<!-- End slides -->
	
	<!-- Start About -->
	<div class="about-section-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12">
					<img src="{% static 'images/about-img.jpg' %}" alt="" class="img-fluid">
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 text-center">
					<div class="inner-column">
						<h1>به رستوران <span>سید جمال الدین خوش آمدید</span></h1>
						<h4>در باره ما</h4>
						<p>این پروژه صرفا برای تحویل درس پروژه انجام شده و هیچ جنبه تجاری ای نخواهد داشت</p>
						<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'reservation:reserve' %}">رزرو میز</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End About -->
	
	<!-- Start QT -->
	<div class="qt-box qt-background">
		<div class="container">
			<div class="row">
				<div class="col-md-8 ml-auto mr-auto text-left">
					<p class="lead ">
						" اگر شما کسی هستید که آشپزی نمیکنید حداقل عقب بایستید و از آشپز تعریف کنید "
					</p>
					<span class="lead">مایکل استراهان</span>
				</div>
			</div>
		</div>
	</div>
	<!-- End QT -->
	
	<!-- Start Menu -->
	<div class="menu-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>منوی مخصوص</h2>
						<p>لیستی از غذای های مخصوص رستوران را ببینید</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="special-menu text-center">
						<div class="button-group filter-button-group">
							<button class="active" data-filter="*">همه</button>
							<button data-filter=".drinks">نوشیدنی ها</button>
							<button data-filter=".lunch">ناهار</button>
							<button data-filter=".dinner">شام</button>
						</div>
					</div>
				</div>
			</div>
				
		<div class="row special-list">


			{% for food in foods %}
				<a href="{% url 'foods:food_details' food.id %}">
					<div class="col-lg-4 col-md-6 special-grid {{food.type_food}}">
						<div class="gallery-single fix">
							<img src="{{food.photo.url}}" class="img-fluid" alt="Image">
							<div class="why-text">
								<h4>{{food.name}}</h4>
								<p>{{food.description}}</p>
								<h5>{{food.price}} تومان</h5>
							</div>
						</div>
					</div>
				</a>
			{% endfor %}
					
				
			</div>
		</div>
	</div>
	<!-- End Menu -->
	
	<!-- Start Gallery -->
	<div class="gallery-box">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>گالری</h2>
						<p>غذاهای ویژه رستوران</p>
					</div>
				</div>
			</div>
			<div class="tz-gallery">
				<div class="row">
					<div class="col-sm-12 col-md-4 col-lg-4">
						<a class="lightbox" href="{% static 'images/gallery-img-01.jpg' %}">
							<img class="img-fluid" src="{% static 'images/gallery-img-01.jpg' %}" alt="Gallery Images">
						</a>
					</div>
					<div class="col-sm-6 col-md-4 col-lg-4">
						<a class="lightbox" href="{% static 'images/gallery-img-02.jpg' %}">
							<img class="img-fluid" src="{% static 'images/gallery-img-02.jpg' %}" alt="Gallery Images">
						</a>
					</div>
					<div class="col-sm-6 col-md-4 col-lg-4">
						<a class="lightbox" href="{% static 'images/gallery-img-03.jpg' %}">
							<img class="img-fluid" src="{% static 'images/gallery-img-03.jpg' %}" alt="Gallery Images">
						</a>
					</div>
					<div class="col-sm-12 col-md-4 col-lg-4">
						<a class="lightbox" href="{% static 'images/gallery-img-04.jpg' %}">
							<img class="img-fluid" src="{% static 'images/gallery-img-04.jpg' %}" alt="Gallery Images">
						</a>
					</div>
					<div class="col-sm-6 col-md-4 col-lg-4">
						<a class="lightbox" href="{% static 'images/gallery-img-05.jpg' %}">
							<img class="img-fluid" src="{% static 'images/gallery-img-05.jpg' %}" alt="Gallery Images">
						</a>
					</div> 
					<div class="col-sm-6 col-md-4 col-lg-4">
						<a class="lightbox" href="{% static 'images/gallery-img-06.jpg' %}">
							<img class="img-fluid" src="{% static 'images/gallery-img-06.jpg' %}" alt="Gallery Images">
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Gallery -->
	
	<!-- Start Customer Reviews -->
	<div class="customer-reviews-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>طراحان</h2>
						<p></p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 mr-auto ml-auto text-center">
					<div id="reviews" class="carousel slide" data-ride="carousel">
						<div class="carousel-inner mt-4">
							<div class="carousel-item text-center active">
								<div class="img-box p-1 border rounded-circle m-auto">
									<img class="d-block w-100 rounded-circle" src="{% static 'images/1.jpg' %}" alt="">
								</div>
								<h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">امیرحسین حق پرستی </strong></h5>
								<h6 class="text-dark m-0">دانشجوی کارشناسی</h6>
								<p class="m-0 pt-3">مشتاق کسب علم</p>
							</div>
							<div class="carousel-item text-center">
								<div class="img-box p-1 border rounded-circle m-auto">
									<img class="d-block w-100 rounded-circle" src="{% static 'images/mamad.jpg' %}" alt="">
								</div>
								<h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">محمد مظفری</strong></h5>
								<h6 class="text-dark m-0">دانشجوی کارشناسی</h6>
								<p class="m-0 pt-3">مشتاق کسب علم</p>
							</div>
							
						</div>
						<a class="carousel-control-prev" href="#reviews" role="button" data-slide="prev">
							<i class="fa fa-angle-left" aria-hidden="true"></i>
							<span class="sr-only">Previous</span>
						</a>
						<a class="carousel-control-next" href="#reviews" role="button" data-slide="next">
							<i class="fa fa-angle-right" aria-hidden="true"></i>
							<span class="sr-only">Next</span>
						</a>
                    </div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Customer Reviews -->
	
	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>تلفن</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>ایمیل</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>مکان</h4>
						<p class="lead">
							اسد آباد
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact info -->

    {% endblock content %}
	
	

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><!-- Basic -->
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
     <!-- Site Metas -->
    <title>Yamifood Restaurant - Responsive HTML5 Template</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="{% static 'image/x-icon' %}">
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css '%}">    
	<!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css '%}">    
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css '%}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css '%}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
	<!-- Start header -->
    {% include "partials/_header.html" %}
	<!-- End header -->
    {% block content %}

    {% endblock content %}

    <!-- Start Footer -->
	{% include "partials/_footer.html" %}
	<!-- End Footer -->
	
	<a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

	<!-- ALL JS FILES -->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
	<script src="{% static 'js/jquery.superslides.min.js' %}"></script>
	<script src="{% static 'js/images-loded.min.js' %}"></script>
	<script src="{% static 'js/isotope.min.js' %}"></script>
	<script src="{% static 'js/baguetteBox.min.js' %}"></script>
	<script src="{% static 'js/form-validator.min.js' %}"></script>
    <script src="{% static 'js/contact-form-script.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

templates/partials/_header.html
{% load static %}
<header class="top-navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'foods:food_list' %}">
                <img src="{% static 'images/logo.png' %}" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbars-rs-food">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a class="nav-link" href="{% url 'foods:food_list' %}">خانه</a></li>
                    <li class="nav-item"><a class="nav-link" href="menu.html">منو</a></li>
                    <li class="nav-item"><a class="nav-link" href="about.html">درباره</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">صفحات</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-a">
                            <a class="dropdown-item" href="{% url 'reservation:reserve' %}">رزرو میز</a>
                            <a class="dropdown-item" href="stuff.html">کارکنان</a>
                            <a class="dropdown-item" href="gallery.html">گالری</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">مقالات</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-a">
                            <a class="dropdown-item" href="{% url 'blog:blog_list' %}">blog</a>
                            <a class="dropdown-item" href="blog-details.html">blog Single</a>
                        </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="contact.html">ارتباط</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>